CREATE DATABASE MBS;

USE MBS;

CREATE DATABASE MBS;

USE MBS;

CREATE TABLE T_MEMBER(
    MEMBER_ID 			VARCHAR(20) PRIMARY KEY,
    NICK_NAME 			VARCHAR(10),
    MEMBER_PW 			VARCHAR(1000),
	MEMBER_NAME 		VARCHAR(50),
	MEMBER_GENDER 		VARCHAR(10),
	MEMBER_BIRTH_Y 		VARCHAR(10),
	MEMBER_BIRTH_M 		VARCHAR(10),
	MEMBER_BIRTH_D 		VARCHAR(10),
	HP1 				VARCHAR(10),
	HP2 				VARCHAR(10),
	HP3 				VARCHAR(10),
	SMS_YN 				VARCHAR(10),
	EMAIL1 				VARCHAR(20),
	EMAIL2 				VARCHAR(20),
	EMAIL_YN 			VARCHAR(10),
	INT_CITY1 			VARCHAR(20),
	INT_GU1 			VARCHAR(20),
	INT_CITY2 			VARCHAR(20),
	INT_GU2 			VARCHAR(20),
	MEMBER_INSTAGRAM	VARCHAR(1000),
	MEMBER_FACEBOOK		VARCHAR(1000),
	ALL_AGREE 			VARCHAR(20),
	SERVICE_AGREE 		VARCHAR(20),
	INFO_AGREE 			VARCHAR(20),
	EXPIR_AGREE 		VARCHAR(20),
	PROM_AGREE 			VARCHAR(20),
    INTEREST_LIST		VARCHAR(1000),
	JOIN_DATE 			DATE
);

CREATE TABLE T_BOARD(
	BOARD_NUMBER 		INT PRIMARY KEY AUTO_INCREMENT,
    NICK_NAME 			VARCHAR(50),
    BOARD_TITLE 		VARCHAR(100),
	CATEGORY_L 			VARCHAR(50),
    CATEGORY_S 			VARCHAR(50),
    PEOPLE_QTY 			INT,
    MEET_DATE 			DATE,
	DATE_NEGO 			VARCHAR(10),
    MEET_TIME 			VARCHAR(10),
	TIME_NEGO 			VARCHAR(10),
	ON_OF 				VARCHAR(50),
	PLACE_ADD 			VARCHAR(100),
	DETAIL_ADD 			VARCHAR(100),
	PLACE_NEGO 			VARCHAR(10),
    URL					VARCHAR(100),
	BOARD_CONTENT 		VARCHAR(1000),
    REPLY				INT,
    VIEWS				INT,
    INTEREST			INT,
    UPLOAD_DATE 		DATE
);

SELECT
		*
FROM
		T_MEMBER;
        
SELECT
		*
FROM
		T_BOARD;
        
delete from
t_board
where	board_number = "7";

SELECT
		BOARD_NUMBER,
		CATEGORY_L,
        CATEGORY_S,
        PEOPLE_QTY,
        BOARD_TITLE,
        MEET_DATE,
        MEET_TIME,
        ON_OF,
        PLACE_ADD,
        REPLY,
        VIEWS,
        INTEREST
FROM	
		T_BOARD;
        
UPDATE 
		T_MEMBER
SET
		MEMBER_INSTAGRAM = "https://www.instagram.com"
WHERE
		MEMBER_ID = 'test1';
	
	